1. What is a Python library? Why do we use Python libraries?

In Python programming, a library is a collection of pre-written, reusable code modules that provide functionality for various tasks. These modules contain functions, classes, and variables that can be imported and used in your own Python programs.

Here are the key reasons why Python libraries are so valuable:

1.Save Time and Effort

2.Enhance Code Quality and Maintainability

3.Access Specialized Functionality

2. What is the difference between Numpy array and List?

NumPy Array: Enforces homogeneity, meaning all elements must be of the same data type (e.g., integers, floats, strings). This uniformity allows for efficient storage and operations.

List: Can hold elements of heterogeneous data types (e.g., mix of integers, strings, booleans) within the same list. This flexibility comes at the cost of less efficient memory usage and certain operations.

3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [5]:
arr.shape

(3, 4)

In [6]:
arr.size

12

In [7]:
arr.ndim

2

4. Write python code to access the first row of the following array?

In [8]:
arr[0]

array([1, 2, 3, 4])

5. How do you access the element at the third row and fourth column from the given numpy array?

In [11]:
arr[2][3]

12

In [13]:
#or

In [12]:
arr[2,3]

12

6. Write code to extract all odd-indexed elements from the given numpy array?

In [17]:
odd_element=arr[arr%2 != 0]
print(odd_element)

[ 1  3  5  7  9 11]


7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?

In [20]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
#or

In [23]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

8. Describe the difference between np.randomrand and np.random.randn ?

In [25]:
 np.random.rand(2,3)

array([[0.38824025, 0.4945125 , 0.93667601],
       [0.55580337, 0.75791802, 0.72471605]])

In [26]:
 np.random.randn(2,3)

array([[-0.1850542 ,  0.94459567, -1.23794994],
       [ 1.08469797,  1.17589651,  0.31000391]])

9. Write code to increase the dimension of the following array?

In [27]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
arr.ndim

2

In [29]:
arr1=np.expand_dims(arr, axis=0)

In [30]:
arr1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [31]:
arr1.ndim

3

10. How to transpose the following array in NumPy?

In [35]:
arr_transpose = arr.T
print(arr_transpose)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consider the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python

Index wise multiplication

In [40]:
a2 = np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])
b2 = np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])

In [41]:
a2*b2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

 Matrix multiplication

In [51]:
a2 = np.array([[1, 2, 3] ,[5, 6, 7],[9, 10, 11]])
b2 = np.array([[1, 2, 3] ,[5, 6, 7],[9, 10, 11]])
c=a2@b2
print(c)

[[ 38  44  50]
 [ 98 116 134]
 [158 188 218]]


Add both the matrics

In [48]:
a2+b2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

subtract matrix B from matrix A

In [49]:
b2-a2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

Divide matrix B by A

In [50]:
b2/a2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

12.  Which function in Numpy can be used to swap the byte order of an array?

To swap the byte order of an array in NumPy, you have a couple of options:

ndarray.byteswap():
    
1.This method allows you to toggle between low-endian and big-endian data representation.

2.It returns a byteswapped array, optionally swapped in-place.

3.The real and imaginary parts of a complex number are swapped individually

In [2]:
import numpy as np
matrix = np.array([[1, 2], [3, 4]], dtype='int16')
swapped_matrix = matrix.byteswap(inplace=False)
print(f"Swapped 2D array: {swapped_matrix}")

Swapped 2D array: [[ 256  512]
 [ 768 1024]]


arr.newbyteorder():

1.You can also change the byte-ordering information in the array dtype.

2.This affects how the array interprets the underlying data as being in a different byte order.

In [7]:
big_end_buffer = bytearray([0, 1, 3, 2])
big_end_arr = np.ndarray(shape=(2,), dtype='>i2', buffer=big_end_buffer)
print(big_end_arr)

[  1 770]


13.  What is the significance of the np.linalg.inv function?

np.linalg.inv is essential for finding the inverse of a matrix, which is crucial for solving various mathematical and scientific problems like:

1.Solving systems of equations

2.Performing geometric transformations

3.Operations in calculus

4.Machine learning algorithms

14. What does the np.reshape function do, and how is it used?

The np.reshape function in NumPy is used to change the shape of an array without modifying its underlying data. It essentially rearranges the elements of the array into a new configuration, as long as the total number of elements remains the same.

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

reshaped_arr = np.reshape(arr, (2, 3))

print("Original array:\n", arr)
print("Reshaped array:\n", reshaped_arr)


Original array:
 [1 2 3 4 5 6]
Reshaped array:
 [[1 2 3]
 [4 5 6]]


15. What is broadcasting in Numpy?

Broadcasting in NumPy refers to a powerful mechanism that allows performing element-wise operations on arrays with different shapes under certain conditions. It essentially "stretches" the smaller array to match the dimensions of the larger array, enabling efficient calculations without explicit loops.

In [8]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([[1], [2], [3]])

added = arr1 + arr2
print(added)


[[2 3 4]
 [3 4 5]
 [4 5 6]]
